### ISSUE TITLE
variable naming is wrong

### ISSUE THREAD

**Issue by cmnstmntmn** [tachyons-css/tachyons-skins#5]
let's say i want to change **mid-gray** class to yellow

``` css
.mid-gray { color: #555; }
```

will become

``` css
.mid-gray { color: yellow; }
```

but this is so wrong! 
- why these variables are named by the value the're holding? 
- how a new skin can be easly created? 

am i missing something?

**Comment by mrmrs** [comment]
If you want to use color: yellow, my advice would be to create new classes for that case. Something like

``` css
.yellow { color: yellow; }
.bg-yellow { background-color: yellow; }
.b--yellow { border-color: yellow; }
```

Does that answer your question?

**Comment by cmnstmntmn** [comment]
well, yes i could.. but still
- this approach generates lots of useless classes, so a [tool](https://github.com/purifycss/purifycss-webpack-plugin) to remove them is required

i'll write my own theme, since i found more useful the approach of using 
generic names for variables like:
- Background
- Primary accent
- Secondary accent
- Error colour
- Success colour

then a a naming convention like

``` css
.primary { color: var(--primary); }
.bg-primary { background-color: var(--primary); }
.b--primary { border-color: var(--primary); }
```

the problem is that nobody will ever know how an element will look by it's classes

``` html
<button class="white bg-primary">Submit</button>
```

but a styleguide should solve that. found [this one](https://github.com/morishitter/postcss-style-guide)
